name: twitch_api
description: A wrapper in pure Dart to connect to Twitch.tv using OAuth implicit
  authentication.
version: 0.6.1
homepage: https://github.com/TesteurManiak/twitch_api_flutter
repository: https://github.com/TesteurManiak/twitch_api_flutter

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dio: ^4.0.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  http_mock_adapter: ^0.3.3
  json_serializable: ^6.5.4
  lint: ^2.0.1
  test: ^1.22.2

false_secrets:
  - /test/**
